Bookstore/Controllers/ShoppingCartController.cs
using Bookstore.Models;
using Bookstore.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bookstore.Controllers
{
    public class ShoppingCartController : Controller
    {
        BookstoreEntities storeDB = new BookstoreEntities();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedBook = storeDB.Books
                .Single(book => book.BookId == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedBook);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string bookName = storeDB.Carts
                .Single(item => item.RecordId == id).Book.Title;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(bookName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

Bookstore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bookstore.Models;

namespace Bookstore.Controllers
{
    public class StoreController : Controller
    {
        BookstoreEntities storeDB= new BookstoreEntities();
        public ActionResult Index()
        {
            var genres = storeDB.Genres.ToList();
            return View(genres);
        }
        public ActionResult Browse(string genre)
        {
            var genreModel = storeDB.Genres.Include("Books")
                .Single(g => g.Name == genre);

            return View(genreModel);
        }
        public ActionResult Search(string searchString)
        {
            var books = from bk in storeDB.Books select bk;
            if (!String.IsNullOrEmpty(searchString))
            {
                books = books.Where(gen => gen.Title.Contains(searchString));
            }

            return View(books);
        }
        public ActionResult Details(int id)
        {
            var book = storeDB.Books.Find(id);
            return View(book);
        }
        // GET: /Store/GenreMenu
        [ChildActionOnly]
        public ActionResult GenreMenu()
        {
            var genres = storeDB.Genres.ToList();
            return PartialView(genres);
        }
    }
}

Bookstore/Views/Store/Browse.cshtml
@model  Bookstore.Models.Genre

@{
    ViewBag.Title = "Browse Albums";
}


<div class="genre">
    <h3><em>@Model.Name</em> Books</h3>

    <ul id="book-list">
        @foreach (var book in Model.Books)
        {
            <li>
                <a href="@Url.Action("Details",new { id = book.BookId })">
                    <img alt="@book.Title"
                         src="@book.BookcoverUrl" />
                    <span>@book.Title</span>
                </a>
            </li>
        }
    </ul>
</div>

Bookstore/Views/Store/Details.cshtml
@model Bookstore.Models.Book
@{
    ViewBag.Title = "Book - " + Model.Title;
}
<h2>@Model.Title</h2>
<p>
    <img alt="@Model.Title"
         src="@Model.BookcoverUrl" />
</p>
<div id="album-details">
    <p>
        <em>Genre:</em>
        @Model.Genre.Name
    </p>
    <p>
        <em>Writer:</em>
        @Model.Writer.Name
    </p>
    <p>
        <em>Price:</em>
        @String.Format("{0:F}",Model.Price)
    </p>
    <p class="button">
        @Html.ActionLink("Add to cart", "AddToCart","ShoppingCart", new { id = Model.BookId }, "")
    </p>
</div>

Bookstore/Views/Store/GenreMenu.cshtml
@model IEnumerable<Bookstore.Models.Genre>
<ul id="categories">
    @foreach (var genre in Model)
    {
        <li>
            @Html.ActionLink(genre.Name,
                "Browse", "Store",
                new { Genre = genre.Name }, null)
    </li>
    }
</ul>

Bookstore/Views/Store/Index.cshtml
@model IEnumerable<Bookstore.Models.Genre> 
@{
    ViewBag.Title = "Store"; 
}
<h3>Browse Genres</h3>
<p> Select from @Model.Count() genres:</p>
<ul>
    @foreach (var genre in Model)
        {
            <li>@Html.ActionLink(genre.Name, "Browse", new { genre = genre.Name })</li>
        }
</ul>

Bookstore/Views/Store/Search.cshtml
@model IEnumerable<Bookstore.Models.Book>

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>
@using (Html.BeginForm())
{
    <p>
        Find by name: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}
@foreach (var item in Model)
{
    <li>
        <a href="@Url.Action("Details",new { id = item.BookId })">
            <img alt="@item.Title"
                 src="@item.BookcoverUrl" />
            <span>@item.Title</span>
        </a>
    </li>
}